= Red Hat - APEX Technical Enablement Plan




Purpose:: 
The purpose of the Red Hat APEX Technical Enablement Plan is to provide our APEX partners an overview of all of the technical resources available to them.  This includes:

* link:slides/red_hat_partner_connect.adoc[Red Hat Partner Connect^]
* link:slides/red_hat_partner_training.adoc[Red Hat Partner Training - OPEN^]
* link:slides/not_for_resale.adoc[Not for Resale (NFR) Subscriptions^]
* link:slides/product_demonstrations.adoc[Product Demonstrations^]
* link:slides/proof_of_concept.adoc[Proof of Concept Requirements and Processes^]
* link:slides/partner_support_resources.adoc[Partner Support Resources^]
* link:slides/product_support_resources.adoc[Product Support Resources^]
* Create a Center of Excellence


Length:: 
1-day with optional 1-hour Wings pre-sales architect training


Audience::  Technical team, Pre-Sales Architects


Outcome:: 
At the end of this 1-day workshop, the partner will be able to modify the provided demonstrations for internal training and/or for their customers.  The partner will also have access to Red Hat’s support environment.   